#!/usr/bin/env bash
# Rebuild the vendored dependency bundles for the docs-organization skill.
#
# lola strips any directory named node_modules from an install, so the two npm
# packages the skill shells out to would never reach an installed copy. They are
# bundled here into vendor/, which lola ships verbatim. vendor/linguist.json is
# not an npm bundle but a build-time fetch of GitHub Linguist's language data,
# also written by this script so `task vendor` remains the single regeneration
# entry point.
#
# Regenerate with `task vendor` after any dependency bump. CI reruns this and
# fails on a non-empty `git diff vendor/`, so a committed bundle can never drift
# from the version .taskfiles/vendor/package.json pins. That toolchain lives
# outside module/ because lola ships every tracked file under the module.
set -euo pipefail
trap 'echo "build-vendor: FAIL at line $LINENO" >&2' ERR

VENDOR_DIR="module/skills/docs-organization/scripts/vendor"
TOOLCHAIN_DIR=".taskfiles/vendor"

[ -d "$TOOLCHAIN_DIR/node_modules" ] || {
  echo "build-vendor: $TOOLCHAIN_DIR/node_modules is missing." >&2
  echo "             Run 'task vendor', which installs the toolchain first." >&2
  exit 2
}

mkdir -p "$VENDOR_DIR"
ENTRY_DIR="$(mktemp -d "$TOOLCHAIN_DIR/.vendor-entry.XXXXXX")"
trap 'rm -rf "$ENTRY_DIR"' EXIT

# esbuild resolves bare specifiers from the entry file's directory, so the
# entry points must live inside the toolchain tree, not in /tmp.
printf "export * from '@aj-archipelago/merval';\n" > "$ENTRY_DIR/merval.mjs"
printf "export { default } from 'markdown-it';\n"  > "$ENTRY_DIR/markdown-it.mjs"

# The pinned esbuild lives in the toolchain tree, not at the repo root this script
# runs from, so invoke it by path rather than letting npx resolve (and fetch) it.
ESBUILD="$TOOLCHAIN_DIR/node_modules/.bin/esbuild"
[ -x "$ESBUILD" ] || {
  echo "build-vendor: $ESBUILD is missing or not executable." >&2
  echo "             Run 'task vendor', which installs the toolchain first." >&2
  exit 2
}

for name in merval markdown-it; do
  "$ESBUILD" \
    --bundle --format=esm --platform=node \
    --outfile="$VENDOR_DIR/$name.mjs" \
    "$ENTRY_DIR/$name.mjs"
done

# Linguist's language/vendor/documentation data classifies source files for
# check-staleness.mjs. Fetched at a pinned tag and verified by SHA-256.
node .taskfiles/scripts/build-linguist-data.mjs "$ENTRY_DIR/linguist-LICENSE"

# esbuild only preserves /*! */ legal comments, and neither package uses them,
# so attribution is assembled here from the installed package metadata.
{
  echo "# Vendored dependency licenses"
  echo
  echo "Generated by \`task vendor\`. Do not edit by hand."
  echo
  echo "\`merval.mjs\` and \`markdown-it.mjs\` are esbuild bundles of the"
  echo "packages below, all MIT-licensed. \`linguist.json\` is data derived"
  echo "from GitHub Linguist (MIT). npm package versions are pinned in"
  echo "\`.taskfiles/vendor/package.json\` in the docs-discipline source repository;"
  echo "the Linguist tag is recorded in \`linguist.json\`'s \`source\` field."
  echo
  for pkg in @aj-archipelago/merval markdown-it argparse entities linkify-it mdurl punycode.js uc.micro; do
    dir="$TOOLCHAIN_DIR/node_modules/$pkg"
    [ -d "$dir" ] || continue
    ver="$(node -p "require('./$dir/package.json').version")"
    lic="$(node -p "require('./$dir/package.json').license || 'see LICENSE file'")"
    echo "## $pkg $ver"
    echo
    echo "License: $lic"
    echo
    for f in LICENSE LICENSE.md LICENSE.txt LICENCE; do
      if [ -f "$dir/$f" ]; then
        echo '```text'
        cat "$dir/$f"
        echo '```'
        echo
        break
      fi
    done
  done
  LINGUIST_SOURCE="$(node -p "require('./$VENDOR_DIR/linguist.json').source")"
  echo "## $LINGUIST_SOURCE (data in \`linguist.json\`)"
  echo
  echo "License: MIT"
  echo
  echo '```text'
  cat "$ENTRY_DIR/linguist-LICENSE"
  echo '```'
  echo
} > "$VENDOR_DIR/LICENSES.md"

echo "build-vendor: wrote $VENDOR_DIR/{merval,markdown-it}.mjs, $VENDOR_DIR/linguist.json, and LICENSES.md"
