#!/usr/bin/env bash
# Rebuild the vendored dependency bundles for the docs-organization skill.
#
# lola strips any directory named node_modules from an install, so the npm
# packages the skill imports would never reach an installed copy. They are
# bundled here into vendor/, which lola ships verbatim. vendor/linguist.json is
# not an npm bundle but a build-time fetch of GitHub Linguist's language data,
# also written by this script so `task vendor` remains the single regeneration
# entry point.
#
# Regenerate with `task vendor` after any dependency bump. CI reruns this and
# fails on a non-empty `git diff vendor/`, so a committed bundle can never drift
# from the version .taskfiles/vendor/package.json pins. That toolchain lives
# outside module/ because lola ships every tracked file under the module.
set -euo pipefail
trap 'echo "build-vendor: FAIL at line $LINENO" >&2' ERR

VENDOR_DIR="module/skills/docs-organization/scripts/vendor"
TOOLCHAIN_DIR=".taskfiles/vendor"

[ -d "$TOOLCHAIN_DIR/node_modules" ] || {
  echo "build-vendor: $TOOLCHAIN_DIR/node_modules is missing." >&2
  echo "             Run 'task vendor', which installs the toolchain first." >&2
  exit 2
}

mkdir -p "$VENDOR_DIR"
# Fixed, not mktemp: esbuild writes the entry file's path into the bundle as a
# comment once the entry has more than a bare re-export (see the markdown-it
# entry below), so a random directory name would make every rebuild differ and
# trip CI's vendor drift check.
ENTRY_DIR="$TOOLCHAIN_DIR/.vendor-entry"
rm -rf "$ENTRY_DIR"
mkdir -p "$ENTRY_DIR"
trap 'rm -rf "$ENTRY_DIR"' EXIT

# esbuild resolves bare specifiers from the entry file's directory, so the
# entry points must live inside the toolchain tree, not in /tmp.
printf "export * from '@aj-archipelago/merval';\n" > "$ENTRY_DIR/merval.mjs"
# markdown-it and the plugins the Markdown adapter applies ship as one bundle,
# so the plugins resolve against the same markdown-it they extend.
cat > "$ENTRY_DIR/markdown-it.mjs" <<'ENTRY'
export { default } from 'markdown-it';
export { default as footnote } from 'markdown-it-footnote';
export { default as container } from 'markdown-it-container';
export { default as admon } from 'markdown-it-admon';
ENTRY
printf "export { load, MemoryLogger } from '@asciidoctor/core';\n" > "$ENTRY_DIR/asciidoctor.mjs"

# The pinned esbuild lives in the toolchain tree, not at the repo root this script
# runs from, so invoke it by path rather than letting npx resolve (and fetch) it.
ESBUILD="$TOOLCHAIN_DIR/node_modules/.bin/esbuild"
[ -x "$ESBUILD" ] || {
  echo "build-vendor: $ESBUILD is missing or not executable." >&2
  echo "             Run 'task vendor', which installs the toolchain first." >&2
  exit 2
}

for name in merval markdown-it asciidoctor; do
  "$ESBUILD" \
    --bundle --format=esm --platform=node \
    --outfile="$VENDOR_DIR/$name.mjs" \
    "$ENTRY_DIR/$name.mjs"
done

# Linguist's language/vendor/documentation data classifies source files for
# check-staleness.mjs. Fetched at a pinned tag and verified by SHA-256.
node .taskfiles/scripts/build-linguist-data.mjs "$ENTRY_DIR/linguist-LICENSE"

# esbuild only preserves /*! */ legal comments, and neither package uses them,
# so attribution is assembled here from the installed package metadata.
{
  echo "# Vendored dependency licenses"
  echo
  echo "Generated by \`task vendor\`. Do not edit by hand."
  echo
  echo "\`merval.mjs\`, \`markdown-it.mjs\`, and \`asciidoctor.mjs\` are esbuild"
  echo "bundles of the packages below; each package's license is listed with it."
  echo "\`linguist.json\` is data derived from GitHub Linguist (MIT). npm"
  echo "package versions are pinned in \`.taskfiles/vendor/package.json\` in"
  echo "the docs-discipline source repository; the Linguist tag is recorded"
  echo "in \`linguist.json\`'s \`source\` field."
  echo
  for pkg in @aj-archipelago/merval markdown-it markdown-it-footnote markdown-it-container markdown-it-admon @asciidoctor/core argparse entities linkify-it mdurl punycode.js uc.micro; do
    dir="$TOOLCHAIN_DIR/node_modules/$pkg"
    [ -d "$dir" ] || continue
    ver="$(node -p "require('./$dir/package.json').version")"
    lic="$(node -p "require('./$dir/package.json').license || 'see LICENSE file'")"
    echo "## $pkg $ver"
    echo
    echo "License: $lic"
    echo
    found=""
    for f in LICENSE LICENSE.md LICENSE.txt LICENCE LICENSE-MIT.txt; do
      if [ -f "$dir/$f" ]; then
        echo '```text'
        cat "$dir/$f"
        echo '```'
        echo
        found=1
        break
      fi
    done
    if [ -z "$found" ]; then
      # Some packages (e.g. @asciidoctor/core) publish no license file in their
      # npm tarball; the text is taken from the source repo at the pinned tag.
      fallback="$TOOLCHAIN_DIR/licenses/${pkg//\//__}.LICENSE"
      if [ -f "$fallback" ]; then
        echo '```text'
        cat "$fallback"
        echo '```'
        echo
      else
        echo "build-vendor: no license text for $pkg $ver; add $TOOLCHAIN_DIR/licenses/${pkg//\//__}.LICENSE from the package's source repo at that version" >&2
        exit 2
      fi
    fi
  done
  LINGUIST_SOURCE="$(node -p "require('./$VENDOR_DIR/linguist.json').source")"
  echo "## $LINGUIST_SOURCE (data in \`linguist.json\`)"
  echo
  echo "License: MIT"
  echo
  echo '```text'
  cat "$ENTRY_DIR/linguist-LICENSE"
  echo '```'
  echo
} > "$VENDOR_DIR/LICENSES.md"

echo "build-vendor: wrote $VENDOR_DIR/{merval,markdown-it,asciidoctor}.mjs, $VENDOR_DIR/linguist.json, and LICENSES.md"
